using Spectre.Console;
using Arkana.Setup.Models;
using Arkana.Setup.UI;

namespace Arkana.Setup.Services;

/// <summary>Guides the user through interactive configuration prompts.</summary>
public static class ConfigGenerator
{
    public static async Task<SetupContext> PromptAsync(SetupContext ctx)
    {
        AnsiConsole.Write(WizardRenderer.Section("Configuration"));
        AnsiConsole.WriteLine();

        // ── Database ──
        AnsiConsole.MarkupLine("[bold]PostgreSQL Database[/]");
        ctx.DbHost = WizardRenderer.PromptWithDefault("Host", ctx.DbHost);
        ctx.DbPort = AnsiConsole.Prompt(
            new TextPrompt<int>("[cyan]Port[/]")
                .DefaultValue(ctx.DbPort)
                .PromptStyle("grey"));
        ctx.DbName = WizardRenderer.PromptWithDefault("Database name", ctx.DbName);
        ctx.DbUser = WizardRenderer.PromptWithDefault("Username", ctx.DbUser);
        ctx.DbPassword = WizardRenderer.PromptSecret("Password", required: true);

        // ── Build connection string and test ──
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine($"[grey]  Connection: {Markup.Escape(ctx.ConnectionString)}[/]");
        AnsiConsole.WriteLine();

        // ── Auth toggle ──
        ctx.AuthEnabled = WizardRenderer.Confirm("Enable dashboard authentication?", false);
        if (ctx.AuthEnabled)
        {
            ctx.AdminUser = WizardRenderer.PromptWithDefault("Admin username", ctx.AdminUser);
            ctx.AdminPassword = WizardRenderer.PromptSecret("Admin password", required: true);
        }

        // ── AI Provider API Keys ──
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine("[bold]AI Provider API Keys[/]");

        ctx.OpenCodeApiKey = WizardRenderer.PromptSecret("OpenCode Go API Key (required)", required: true);

        if (WizardRenderer.Confirm("Configure OpenAI?", false))
            ctx.OpenAiApiKey = WizardRenderer.PromptSecret("OpenAI API Key", required: false);

        if (WizardRenderer.Confirm("Configure Anthropic?", false))
            ctx.AnthropicApiKey = WizardRenderer.PromptSecret("Anthropic API Key", required: false);

        if (WizardRenderer.Confirm("Configure Gemini?", false))
            ctx.GeminiApiKey = WizardRenderer.PromptSecret("Gemini API Key", required: false);

        // ── Summary ──
        AnsiConsole.WriteLine();
        var summary = new List<(string, string)>
        {
            ("Database", $"{ctx.DbHost}:{ctx.DbPort}/{ctx.DbName}"),
            ("Auth Enabled", ctx.AuthEnabled ? $"Yes (admin: {ctx.AdminUser})" : "No"),
            ("OpenCode", ctx.OpenCodeApiKey.Length > 8
                ? $"{ctx.OpenCodeApiKey[..8]}...{ctx.OpenCodeApiKey[^4..]}"
                : "configured"),
            ("OpenAI", ctx.OpenAiApiKey is { Length: > 0 } ? "configured" : "skipped"),
            ("Anthropic", ctx.AnthropicApiKey is { Length: > 0 } ? "configured" : "skipped"),
            ("Gemini", ctx.GeminiApiKey is { Length: > 0 } ? "configured" : "skipped"),
        };

        WizardRenderer.ResultsTable("Configuration Summary", summary);
        AnsiConsole.WriteLine();

        if (!WizardRenderer.Confirm("Proceed with this configuration?"))
        {
            AnsiConsole.MarkupLine("[red]Setup cancelled by user.[/]");
            Environment.Exit(0);
        }

        await GenerateEnvFileAsync(ctx);
        await UpdateAppSettingsAsync(ctx);

        return ctx;
    }

    private static async Task GenerateEnvFileAsync(SetupContext ctx)
    {
        var envPath = Path.Combine(ctx.DeployDir, ".env");
        var envExample = Path.Combine(ctx.DeployDir, ".env.example");

        // Load template from .env.example if exists
        string template;
        if (File.Exists(envExample))
            template = await File.ReadAllTextAsync(envExample);
        else
            template = @"# ARKANA GATEWAY — Environment Configuration
# Generated by arkana setup

OPENCODE_GO_API_KEY={OpenCodeApiKey}

# Authentication (optional)
AUTH={AuthEnabled}

# PostgreSQL
ConnectionStrings__Postgres={ConnectionString}
";

        // Replace placeholders
        template = template
            .Replace("{OpenCodeApiKey}", ctx.OpenCodeApiKey)
            .Replace("{ConnectionString}", ctx.ConnectionString)
            .Replace("{AuthEnabled}", ctx.AuthEnabled ? "1" : "0");

        if (ctx.OpenAiApiKey is { Length: > 0 })
            template += $"\nOPENAI_API_KEY={ctx.OpenAiApiKey}";
        if (ctx.AnthropicApiKey is { Length: > 0 })
            template += $"\nANTHROPIC_API_KEY={ctx.AnthropicApiKey}";
        if (ctx.GeminiApiKey is { Length: > 0 })
            template += $"\nGEMINI_API_KEY={ctx.GeminiApiKey}";

        await File.WriteAllTextAsync(envPath, template);
        WizardRenderer.Success($".env saved to [grey]{envPath}[/]");
    }

    private static async Task UpdateAppSettingsAsync(SetupContext ctx)
    {
        var appSettingsPath = Path.Combine(
            ctx.SolutionDir, "src", "Arkana.Gateway.Api", "appsettings.json");

        if (!File.Exists(appSettingsPath)) return;

        var json = await File.ReadAllTextAsync(appSettingsPath);

        // Update connection string
        json = System.Text.RegularExpressions.Regex.Replace(
            json,
            "\"Postgres\"\\s*:\\s*\"[^\"]*\"",
            $"\"Postgres\": \"{ctx.ConnectionString}\"");

        // Update auth enabled
        json = System.Text.RegularExpressions.Regex.Replace(
            json,
            "\"Enabled\"\\s*:\\s*(true|false)",
            $"\"Enabled\": {ctx.AuthEnabled.ToString().ToLowerInvariant()}");

        await File.WriteAllTextAsync(appSettingsPath, json);
        WizardRenderer.Success($"appsettings.json updated");
    }
}
