#!/usr/bin/env bash
# Add a Gemini/Antigravity broker slot on this host.
#
# Ops placement: copy this file (with cliproxy-entrypoint.sh and
# config.template.yaml) to <deploy-dir>/gemini-slots/ and run it there:
#
#   ./add-slot.sh b        # create/refresh slot b and start its broker
#   ./add-slot.sh d e f    # several slots at once
#   ./add-slot.sh b --wire # also wire the slot into the gateway compose and
#                          # recreate the gateway
#
# Each slot is one isolated CLIProxyAPI instance with its own auth volume
# (one Google identity per slot) and its own management key in <deploy-dir>/.env.
# Slot "a" is expected to be the pre-existing broker on the host and is left
# alone. Re-running never disturbs an existing slot: its auth volume survives,
# so a signed-in Google account stays signed in.
set -euo pipefail
SLOTS_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SLOTS_DIR/.." && pwd)"
ENV_FILE="$DEPLOY_DIR/.env"
COMPOSE_FILE="$SLOTS_DIR/docker-compose.gemini-slots.yml"
GATEWAY_COMPOSE="$DEPLOY_DIR/docker-compose.yml"
IMAGE="${BROKER_IMAGE:-cliproxy-api-antigravity:942282e}"
REDIRECT_URI="${ANTIGRAVITY_REDIRECT_URI:-https://gateway.arkana.dev/oauth/gemini/callback}"
NETWORK="${GEMINI_BROKER_NETWORK:-arkana-dev_arkana-net}"
WIRE=0
ARGS=()
for a in "$@"; do
  if [ "$a" = "--wire" ]; then WIRE=1; else ARGS+=("$a"); fi
done
[ "${#ARGS[@]}" -gt 0 ] || { echo "usage: $0 <slot-letter> [more...] [--wire]" >&2; exit 2; }
for s in "${ARGS[@]}"; do
  case "$s" in [a-z]) ;; *) echo "slot name must be a single lowercase letter (got '$s')" >&2; exit 2;; esac
done

set -a; . "$ENV_FILE"; set +a
CLIENT_ID="${OAUTH_GEMINI_CLIENT_ID:?OAUTH_GEMINI_CLIENT_ID missing from .env}"
CLIENT_SECRET="${OAUTH_GEMINI_CLIENT_SECRET:?OAUTH_GEMINI_CLIENT_SECRET missing from .env}"

# ── 1. per-slot management key in .env (generated once) ──
for s in "${ARGS[@]}"; do
  U="$(echo "$s" | tr '[:lower:]' '[:upper:]')"
  if ! grep -q "^GEMINI_BROKER_${U}_MANAGEMENT_KEY=" "$ENV_FILE"; then
    printf 'GEMINI_BROKER_%s_MANAGEMENT_KEY=%s\n' "$U" "$(openssl rand -hex 32)" >> "$ENV_FILE"
    echo "generated GEMINI_BROKER_${U}_MANAGEMENT_KEY"
  else
    echo "key for slot $s already present"
  fi
done
set -a; . "$ENV_FILE"; set +a

# ── 2. render the overlay with every known slot (a stays on the legacy broker) ──
KEY_SLOTS=""
for s in "${ARGS[@]}"; do KEY_SLOTS="$KEY_SLOTS $s"; done
# discover previously generated slots so re-runs keep them
for k in $(grep -oE '^GEMINI_BROKER_[A-Z]_MANAGEMENT_KEY=' "$ENV_FILE" | tr -d '=' | sed -E 's/GEMINI_BROKER_(.*)_MANAGEMENT_KEY/\1/' | tr 'A-Z' 'a-z'); do
  # slot "a" is served by the legacy cliproxy container on this host; a
  # second gemini-broker-a here would conflict with it.
  [ "$k" = "a" ] && continue
  case " $KEY_SLOTS " in *" $k "*) ;; *) KEY_SLOTS="$KEY_SLOTS $k";; esac
done

{
  cat <<YAML
# Generated by add-slot.sh - one isolated broker instance per Antigravity slot.
# Each slot keeps its own auth volume (Google identity) and management key.
services:
YAML
  for s in $KEY_SLOTS; do
    U="$(echo "$s" | tr '[:lower:]' '[:upper:]')"
    cat <<YAML
  gemini-broker-$s:
    image: $IMAGE
    container_name: gemini-broker-$s
    environment:
      ANTIGRAVITY_OAUTH_CLIENT_ID: "$CLIENT_ID"
      ANTIGRAVITY_OAUTH_CLIENT_SECRET: "$CLIENT_SECRET"
      ANTIGRAVITY_OAUTH_REDIRECT_URI: "$REDIRECT_URI"
      CLIPROXY_MANAGEMENT_KEY: "\${GEMINI_BROKER_${U}_MANAGEMENT_KEY}"
      # Optional split: set GEMINI_BROKER_<SLOT>_DATA_PLANE_KEY in .env to give the data
      # plane its own secret. Empty means the entrypoint reuses the management key, which
      # is what the gateway sends (slot DataPlaneKey falls back to ManagementKey).
      CLIPROXY_DATA_PLANE_KEY: "\${GEMINI_BROKER_${U}_DATA_PLANE_KEY:-}"
      CLIPROXY_CONFIG_PATH: /etc/cliproxy/config.yaml
      CLIPROXY_CONFIG_TEMPLATE: /usr/local/share/cliproxy/config.template.yaml
      TZ: Asia/Shanghai
    entrypoint: ["/usr/local/bin/cliproxy-entrypoint"]
    expose: ["8317"]
    volumes:
      - gemini_slot_${s}_auth:/root/.cli-proxy-api
      - gemini_slot_${s}_config:/etc/cliproxy
      - $SLOTS_DIR/cliproxy-entrypoint.sh:/usr/local/bin/cliproxy-entrypoint:ro
      - $SLOTS_DIR/config.template.yaml:/usr/local/share/cliproxy/config.template.yaml:ro
    command: ["-config", "/etc/cliproxy/config.yaml"]
    restart: unless-stopped
    networks: [arkana-net]
YAML
  done
  printf 'volumes:\n'
  for s in $KEY_SLOTS; do
    printf '  gemini_slot_%s_auth:\n    name: arkana-gemini-slot-%s-auth\n' "$s" "$s"
    printf '  gemini_slot_%s_config:\n    name: arkana-gemini-slot-%s-config\n' "$s" "$s"
  done
  printf 'networks:\n  arkana-net:\n    external: true\n    name: %s\n' "$NETWORK"
} > "$COMPOSE_FILE"
echo "rendered $COMPOSE_FILE for slots:$KEY_SLOTS"

# ── 3. start the new brokers ──
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d $(for s in "${ARGS[@]}"; do printf 'gemini-broker-%s ' "$s"; done)
sleep 4
for s in "${ARGS[@]}"; do
  U="$(echo "$s" | tr '[:lower:]' '[:upper:]')"
  KEY="$(grep -E "^GEMINI_BROKER_${U}_MANAGEMENT_KEY=" "$ENV_FILE" | cut -d= -f2-)"
  # The broker image ships no HTTP client, so probe from the host against the
  # container IP instead of exec-ing curl inside the slot.
  for _ in $(seq 1 20); do
    IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "gemini-broker-$s" 2>/dev/null || true)"
    [ -n "$IP" ] && curl -sS -m 3 -o /dev/null "http://$IP:8317/" 2>/dev/null && break
    sleep 3
  done
  STATUS="$(docker inspect -f '{{.State.Status}}' "gemini-broker-$s" 2>/dev/null || echo missing)"
  IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "gemini-broker-$s" 2>/dev/null || true)"
  MGMT="err"
  if [ -n "$IP" ]; then
    for _ in $(seq 1 10); do
      MGMT="$(curl -sS -m 5 -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $KEY" "http://$IP:8317/v0/management/auth-files" 2>/dev/null || echo err)"
      [ "$MGMT" = "200" ] && break
      sleep 2
    done
  fi
  echo "slot $s: status=$STATUS management_api=$MGMT ip=$IP"
done

# ── 4. gateway wiring lines ──
echo
echo "Gateway wiring (add to $GATEWAY_COMPOSE under the gateway service):"
for s in "${ARGS[@]}"; do
  U="$(echo "$s" | tr '[:lower:]' '[:upper:]')"
  printf '      GeminiBroker__Slots__gemini-broker-%s__BaseUrl: http://gemini-broker-%s:8317\n' "$s" "$s"
  printf '      GeminiBroker__Slots__gemini-broker-%s__ManagementKey: ${GEMINI_BROKER_%s_MANAGEMENT_KEY}\n' "$s" "$U"
done
if [ "$WIRE" = 1 ]; then
  python3 - "$GATEWAY_COMPOSE" "$GATEWAY_COMPOSE.bak-slots-$(date -u +%Y%m%dT%H%M%SZ)" "$*" <<'PY'
import sys, shutil
path, backup, _ = sys.argv[1], sys.argv[2], sys.argv[3]
shutil.copy(path, backup)
print(f"backup -> {backup}")
PY
  for s in "${ARGS[@]}"; do
    U="$(echo "$s" | tr '[:lower:]' '[:upper:]')"
    if ! grep -q "gemini-broker-${s}__BaseUrl" "$GATEWAY_COMPOSE"; then
      python3 - "$GATEWAY_COMPOSE" "$s" "$U" <<'PY'
import sys
path, slot, up = sys.argv[1], sys.argv[2], sys.argv[3]
lines = open(path, encoding='utf-8').read().split('\n')
anchor = next(i for i, l in enumerate(lines) if l.strip().startswith('GeminiBroker__Timeout'))
lines[anchor + 1:anchor + 1] = [
    f'      GeminiBroker__Slots__gemini-broker-{slot}__BaseUrl: http://gemini-broker-{slot}:8317',
    f'      GeminiBroker__Slots__gemini-broker-{slot}__ManagementKey: ${{GEMINI_BROKER_{up}_MANAGEMENT_KEY}}',
]
open(path, 'w', encoding='utf-8').write('\n'.join(lines))
print(f'wired slot {slot} into the gateway compose')
PY
    else
      echo "slot $s already wired"
    fi
  done
  cd "$DEPLOY_DIR"
  docker compose up -d --no-build --no-deps gateway
  for _ in $(seq 1 24); do
    [ "$(docker inspect -f '{{.State.Health.Status}}' arkana-gateway 2>/dev/null || true)" = healthy ] && break
    sleep 5
  done
  echo "gateway health=$(docker inspect -f '{{.State.Health.Status}}' arkana-gateway)"

  # Guard: the streaming path needs GeminiSubscription__ProviderId. Verify the
  # recreated gateway actually carries it (and every slot we just wired).
  missing=""
  docker exec arkana-gateway printenv GeminiSubscription__ProviderId >/dev/null 2>&1 || missing="$missing GeminiSubscription__ProviderId"
  for s in "${ARGS[@]}"; do
    docker exec arkana-gateway printenv "GeminiBroker__Slots__gemini-broker-${s}__BaseUrl" >/dev/null 2>&1 || missing="$missing GeminiBroker__Slots__gemini-broker-${s}__BaseUrl"
  done
  if [ -n "$missing" ]; then
    echo "WARNING: gateway is missing required env:$missing" >&2
    echo "         add the compose lines (see README) and recreate the gateway before use." >&2
  else
    echo "gateway env verified: ProviderId + all wired slots present"
  fi
fi
