// <auto-generated />
using System;
using Arkana.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arkana.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260628043944_AddPolicyTemplates")]
    partial class AddPolicyTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arkana.Domain.Entities.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("CostPerInputToken")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostPerOutputToken")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTokensPerRequest")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AiProviders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BaseUrl = "http://localhost:8080",
                            Code = "opencode",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "OpenCode",
                            Priority = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Code = "openai",
                            CostPerInputToken = 0.0000025m,
                            CostPerOutputToken = 0.00001m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "OpenAI",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Code = "gemini",
                            CostPerInputToken = 0.00000125m,
                            CostPerOutputToken = 0.000005m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Code = "anthropic",
                            CostPerInputToken = 0.000003m,
                            CostPerOutputToken = 0.000015m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Anthropic",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            BaseUrl = "http://localhost:11434",
                            Code = "ollama",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Ollama",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            BaseUrl = "https://api.deepseek.com/v1",
                            Code = "deepseek",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek Direct",
                            Priority = 0
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("RateLimitMaxConcurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.DashboardUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Admin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("DashboardUsers");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.GlobalRateLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultMaxConcurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("DefaultRequestsPerMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<int>("DefaultTokensPerMinute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000000);

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GlobalRateLimits");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("CostPerInputToken")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("CostPerOutputToken")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTokensPerRequest")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Code")
                        .IsUnique();

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Code = "deepseek-v4-flash",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Code = "deepseek-v4-pro",
                            CostPerInputToken = 0.00000174m,
                            CostPerOutputToken = 0.00000348m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Code = "glm-5.1",
                            CostPerInputToken = 0.00000140m,
                            CostPerOutputToken = 0.00000440m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "GLM-5.1",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Code = "glm-5",
                            CostPerInputToken = 0.00000100m,
                            CostPerOutputToken = 0.00000320m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "GLM-5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Code = "kimi-k2.5",
                            CostPerInputToken = 0.00000060m,
                            CostPerOutputToken = 0.00000300m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kimi K2.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Code = "kimi-k2.6",
                            CostPerInputToken = 0.00000095m,
                            CostPerOutputToken = 0.00000400m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kimi K2.6",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Code = "mimo-v2.5",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "MiMo V2.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Code = "mimo-v2.5-pro",
                            CostPerInputToken = 0.00000174m,
                            CostPerOutputToken = 0.00000348m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "MiMo V2.5 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Code = "gpt-4o",
                            CostPerInputToken = 0.0000025m,
                            CostPerOutputToken = 0.00001m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4o",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            Code = "gpt-4o-mini",
                            CostPerInputToken = 0.00000015m,
                            CostPerOutputToken = 0.0000006m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4o Mini",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            Code = "gpt-4.1",
                            CostPerInputToken = 0.000002m,
                            CostPerOutputToken = 0.000008m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4.1",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            Code = "o3",
                            CostPerInputToken = 0.00001m,
                            CostPerOutputToken = 0.00004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "O3",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            Code = "o4-mini",
                            CostPerInputToken = 0.0000011m,
                            CostPerOutputToken = 0.0000044m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "O4 Mini",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            Code = "gemini-2.5-pro",
                            CostPerInputToken = 0.00000125m,
                            CostPerOutputToken = 0.000005m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.5 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            Code = "gemini-2.5-flash",
                            CostPerInputToken = 0.000000075m,
                            CostPerOutputToken = 0.0000003m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.5 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            Code = "gemini-2.0-flash",
                            CostPerInputToken = 0.0000001m,
                            CostPerOutputToken = 0.0000004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.0 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000031"),
                            Code = "claude-sonnet-4",
                            CostPerInputToken = 0.000003m,
                            CostPerOutputToken = 0.000015m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Sonnet 4",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000032"),
                            Code = "claude-haiku-3.5",
                            CostPerInputToken = 0.0000008m,
                            CostPerOutputToken = 0.000004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Haiku 3.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000033"),
                            Code = "claude-opus-4",
                            CostPerInputToken = 0.000015m,
                            CostPerOutputToken = 0.000075m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Opus 4",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000041"),
                            Code = "llama-3.1-8b",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Llama 3.1 8B",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000042"),
                            Code = "llama-3.1-70b",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Llama 3.1 70B",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000043"),
                            Code = "mistral",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Mistral",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000044"),
                            Code = "codellama",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "CodeLlama",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000051"),
                            Code = "deepseek-v4-flash-direct",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Flash (Direct)",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000052"),
                            Code = "deepseek-v4-pro-direct",
                            CostPerInputToken = 0.00000174m,
                            CostPerOutputToken = 0.00000348m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Pro (Direct)",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<long>("IncludedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("IncludedOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxApiKeys")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTokensPerMinute")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            Features = "{\"semantic_cache\":false,\"streaming\":true,\"embeddings\":false}",
                            IncludedInputTokens = 0L,
                            IncludedOutputTokens = 0L,
                            IsActive = true,
                            MaxApiKeys = 2,
                            MaxConcurrent = 2,
                            MaxRequestsPerMinute = 10,
                            MaxTokensPerMinute = 100000,
                            MonthlyPrice = 0m,
                            Name = "Free",
                            Slug = "free"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            Features = "{\"semantic_cache\":true,\"streaming\":true,\"embeddings\":true}",
                            IncludedInputTokens = 1000000L,
                            IncludedOutputTokens = 500000L,
                            IsActive = true,
                            MaxApiKeys = 10,
                            MaxConcurrent = 5,
                            MaxRequestsPerMinute = 60,
                            MaxTokensPerMinute = 1000000,
                            MonthlyPrice = 29.99m,
                            Name = "Pro",
                            Slug = "pro"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            Features = "{\"semantic_cache\":true,\"streaming\":true,\"embeddings\":true}",
                            IncludedInputTokens = 10000000L,
                            IncludedOutputTokens = 5000000L,
                            IsActive = true,
                            MaxApiKeys = 100,
                            MaxConcurrent = 25,
                            MaxRequestsPerMinute = 300,
                            MaxTokensPerMinute = 10000000,
                            MonthlyPrice = 199.99m,
                            Name = "Enterprise",
                            Slug = "enterprise"
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.PolicyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PolicyTemplates");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Default Tenant",
                            Slug = "default"
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.TenantBudget", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("MonthlyInputTokenCap")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyOutputTokenCap")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RemainingInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("RemainingOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId");

                    b.ToTable("TenantBudgets");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            MonthlyInputTokenCap = 1000000L,
                            MonthlyOutputTokenCap = 500000L,
                            PeriodEnd = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PeriodStart = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingInputTokens = 1000000L,
                            RemainingOutputTokens = 500000L,
                            RowVersion = 0u
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.TenantPlan", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OverrideIncludedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("OverrideIncludedOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int?>("OverrideMaxApiKeys")
                        .HasColumnType("integer");

                    b.Property<int?>("OverrideMaxConcurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("OverrideMaxRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("OverrideMaxTpm")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.HasIndex("PlanId");

                    b.ToTable("TenantPlans");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PlanId = new Guid("f0000000-0000-0000-0000-000000000002"),
                            StartsAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Arkana.Infrastructure.Persistence.Entities.RequestLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(20,10)");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Arkana.Infrastructure.Persistence.Entities.TokenUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(20,10)");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TokenUsages");
                });

            modelBuilder.Entity("ApiKeyModel", b =>
                {
                    b.Property<Guid>("AllowedByKeysId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllowedModelsId")
                        .HasColumnType("uuid");

                    b.HasKey("AllowedByKeysId", "AllowedModelsId");

                    b.HasIndex("AllowedModelsId");

                    b.ToTable("ApiKeyModels", (string)null);
                });

            modelBuilder.Entity("Arkana.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.DashboardUser", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DashboardUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Model", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.TenantBudget", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Budget")
                        .HasForeignKey("Arkana.Domain.Entities.TenantBudget", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.TenantPlan", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.Plan", "Plan")
                        .WithMany("TenantAssignments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arkana.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Plan")
                        .HasForeignKey("Arkana.Domain.Entities.TenantPlan", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ApiKeyModel", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("AllowedByKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkana.Domain.Entities.Model", null)
                        .WithMany()
                        .HasForeignKey("AllowedModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arkana.Domain.Entities.AiProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Plan", b =>
                {
                    b.Navigation("TenantAssignments");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Budget");

                    b.Navigation("DashboardUsers");

                    b.Navigation("Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
