// <auto-generated />
using Arkana.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Arkana.Infrastructure.Migrations;

[DbContext(typeof(GatewayDbContext))]
[Migration("20260910000000_RemoveOrphanedExpectedAccountVersion")]
public partial class RemoveOrphanedExpectedAccountVersion
{
}
