// <auto-generated />
using System;
using Arkana.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arkana.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260607173444_AddApiKeyKeyPrefix")]
    partial class AddApiKeyKeyPrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arkana.Domain.Entities.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("CostPerInputToken")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostPerOutputToken")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTokensPerRequest")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AiProviders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BaseUrl = "http://localhost:8080",
                            Code = "opencode",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "OpenCode",
                            Priority = 0
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Code = "openai",
                            CostPerInputToken = 0.0000025m,
                            CostPerOutputToken = 0.00001m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "OpenAI",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Code = "gemini",
                            CostPerInputToken = 0.00000125m,
                            CostPerOutputToken = 0.000005m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Code = "anthropic",
                            CostPerInputToken = 0.000003m,
                            CostPerOutputToken = 0.000015m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Anthropic",
                            Priority = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            BaseUrl = "http://localhost:11434",
                            Code = "ollama",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Ollama",
                            Priority = 2
                        });
                });

            modelBuilder.Entity("Arkana.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("CostPerInputToken")
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("CostPerOutputToken")
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTokensPerRequest")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Code")
                        .IsUnique();

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Code = "deepseek-v4-flash",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Code = "deepseek-v4-pro",
                            CostPerInputToken = 0.00000174m,
                            CostPerOutputToken = 0.00000348m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "DeepSeek V4 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Code = "glm-5.1",
                            CostPerInputToken = 0.00000140m,
                            CostPerOutputToken = 0.00000440m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "GLM-5.1",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Code = "glm-5",
                            CostPerInputToken = 0.00000100m,
                            CostPerOutputToken = 0.00000320m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "GLM-5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Code = "kimi-k2.5",
                            CostPerInputToken = 0.00000060m,
                            CostPerOutputToken = 0.00000300m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kimi K2.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Code = "kimi-k2.6",
                            CostPerInputToken = 0.00000095m,
                            CostPerOutputToken = 0.00000400m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kimi K2.6",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Code = "mimo-v2.5",
                            CostPerInputToken = 0.00000014m,
                            CostPerOutputToken = 0.00000028m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "MiMo V2.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Code = "mimo-v2.5-pro",
                            CostPerInputToken = 0.00000174m,
                            CostPerOutputToken = 0.00000348m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "MiMo V2.5 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Code = "gpt-4o",
                            CostPerInputToken = 0.0000025m,
                            CostPerOutputToken = 0.00001m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4o",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            Code = "gpt-4o-mini",
                            CostPerInputToken = 0.00000015m,
                            CostPerOutputToken = 0.0000006m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4o Mini",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            Code = "gpt-4.1",
                            CostPerInputToken = 0.000002m,
                            CostPerOutputToken = 0.000008m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "GPT-4.1",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            Code = "o3",
                            CostPerInputToken = 0.00001m,
                            CostPerOutputToken = 0.00004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "O3",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            Code = "o4-mini",
                            CostPerInputToken = 0.0000011m,
                            CostPerOutputToken = 0.0000044m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "O4 Mini",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            Code = "gemini-2.5-pro",
                            CostPerInputToken = 0.00000125m,
                            CostPerOutputToken = 0.000005m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.5 Pro",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            Code = "gemini-2.5-flash",
                            CostPerInputToken = 0.000000075m,
                            CostPerOutputToken = 0.0000003m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.5 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            Code = "gemini-2.0-flash",
                            CostPerInputToken = 0.0000001m,
                            CostPerOutputToken = 0.0000004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Gemini 2.0 Flash",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000031"),
                            Code = "claude-sonnet-4",
                            CostPerInputToken = 0.000003m,
                            CostPerOutputToken = 0.000015m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Sonnet 4",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000032"),
                            Code = "claude-haiku-3.5",
                            CostPerInputToken = 0.0000008m,
                            CostPerOutputToken = 0.000004m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Haiku 3.5",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000033"),
                            Code = "claude-opus-4",
                            CostPerInputToken = 0.000015m,
                            CostPerOutputToken = 0.000075m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Claude Opus 4",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000041"),
                            Code = "llama-3.1-8b",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Llama 3.1 8B",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000042"),
                            Code = "llama-3.1-70b",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Llama 3.1 70B",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000043"),
                            Code = "mistral",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Mistral",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000044"),
                            Code = "codellama",
                            CostPerInputToken = 0m,
                            CostPerOutputToken = 0m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "CodeLlama",
                            ProviderId = new Guid("a1000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("Arkana.Infrastructure.Persistence.Entities.RequestLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(20,10)");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("Timestamp");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Arkana.Infrastructure.Persistence.Entities.TokenUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(20,10)");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("Timestamp");

                    b.ToTable("TokenUsages");
                });

            modelBuilder.Entity("ApiKeyModel", b =>
                {
                    b.Property<Guid>("AllowedByKeysId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllowedModelsId")
                        .HasColumnType("uuid");

                    b.HasKey("AllowedByKeysId", "AllowedModelsId");

                    b.HasIndex("AllowedModelsId");

                    b.ToTable("ApiKeyModels", (string)null);
                });

            modelBuilder.Entity("Arkana.Domain.Entities.Model", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("ApiKeyModel", b =>
                {
                    b.HasOne("Arkana.Domain.Entities.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("AllowedByKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arkana.Domain.Entities.Model", null)
                        .WithMany()
                        .HasForeignKey("AllowedModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Arkana.Domain.Entities.AiProvider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
