using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;

namespace Arkana.Infrastructure.Security;

/// <summary>
/// Resolves the 32-byte master key used to wrap Data Encryption Keys (DEKs).
///
/// Resolution order:
///   1. <c>ARKANA_MASTER_KEY</c> env var (Base64, must decode to 32 bytes)
///   2. <c>ARKANA_MASTER_KEY_FILE</c> env var (path to a 32-byte binary file)
///   3. Auto-generate and persist to <c>{DataDir}/master.key</c> with 0600 perms
///
/// Option 3 is only safe for single-host local development. In production,
/// the master key MUST be supplied out-of-band (KMS, HashiCorp Vault, sealed secret, etc.).
/// </summary>
public static class MasterKeyProvider
{
    public const string EnvVar = "ARKANA_MASTER_KEY";
    public const string EnvFileVar = "ARKANA_MASTER_KEY_FILE";
    public const int KeySizeBytes = 32; // AES-256

    /// <summary>
    /// Loads or generates the master key. The returned byte array is a fresh copy —
    /// callers are responsible for zeroing it after use.
    /// </summary>
    public static (byte[] Key, MasterKeySource Source) Resolve(
        string? dataDir,
        ILogger? logger = null)
    {
        // 1. Inline env var
        var inline = Environment.GetEnvironmentVariable(EnvVar);
        if (!string.IsNullOrWhiteSpace(inline))
        {
            try
            {
                var key = Convert.FromBase64String(inline);
                if (key.Length != KeySizeBytes)
                {
                    Array.Clear(key);
                    throw new InvalidOperationException(
                        $"{EnvVar} must decode to {KeySizeBytes} bytes. Got {key.Length}.");
                }
                logger?.LogInformation(
                    "Master key loaded from {EnvVar} env var ({Bytes} bytes).", EnvVar, key.Length);
                return (key, MasterKeySource.EnvironmentVariable);
            }
            catch (FormatException ex)
            {
                throw new InvalidOperationException(
                    $"{EnvVar} is not valid Base64. " +
                    $"Generate one with: openssl rand -base64 {KeySizeBytes}", ex);
            }
        }

        // 2. File path env var
        var filePath = Environment.GetEnvironmentVariable(EnvFileVar);
        if (!string.IsNullOrWhiteSpace(filePath))
        {
            if (!File.Exists(filePath))
                throw new InvalidOperationException(
                    $"{EnvFileVar} points to '{filePath}' which does not exist.");
            var key = File.ReadAllBytes(filePath);
            if (key.Length != KeySizeBytes)
            {
                Array.Clear(key);
                throw new InvalidOperationException(
                    $"Master key file '{filePath}' must be exactly {KeySizeBytes} bytes. Got {key.Length}.");
            }
            logger?.LogInformation(
                "Master key loaded from {EnvFileVar}={FilePath} ({Bytes} bytes).",
                EnvFileVar, filePath, key.Length);
            return (key, MasterKeySource.File);
        }

        // 3. Auto-generate (with strong warning)
        if (string.IsNullOrEmpty(dataDir))
            dataDir = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "Arkana");

        Directory.CreateDirectory(dataDir);
        var defaultPath = Path.Combine(dataDir, "master.key");

        if (File.Exists(defaultPath))
        {
            var existing = File.ReadAllBytes(defaultPath);
            if (existing.Length != KeySizeBytes)
            {
                Array.Clear(existing);
                throw new InvalidOperationException(
                    $"Existing master key at '{defaultPath}' is {existing.Length} bytes; " +
                    $"expected {KeySizeBytes}. Refusing to start — manual recovery required.");
            }
            logger?.LogWarning(
                "Using existing master key at {Path}. " +
                "BACK UP THIS FILE — losing it makes all stored credentials unrecoverable.",
                defaultPath);
            return (existing, MasterKeySource.AutoGeneratedFile);
        }

        var newKey = RandomNumberGenerator.GetBytes(KeySizeBytes);
        File.WriteAllBytes(defaultPath, newKey);

        // Best-effort 0600 on Unix. No-op on Windows.
        try
        {
            if (!OperatingSystem.IsWindows())
            {
                File.SetUnixFileMode(defaultPath,
                    UnixFileMode.UserRead | UnixFileMode.UserWrite);
            }
        }
        catch (Exception ex)
        {
            logger?.LogWarning(ex,
                "Could not set 0600 permissions on master key file at {Path}. " +
                "On multi-user systems this is a security risk — set permissions manually.",
                defaultPath);
        }

        logger?.LogWarning(
            "Auto-generated master key at {Path}. " +
            "BACK UP THIS FILE — losing it makes all stored credentials unrecoverable. " +
            "For production, set {EnvVar} or {EnvFileVar} instead.",
            defaultPath, EnvVar, EnvFileVar);

        return (newKey, MasterKeySource.AutoGeneratedFile);
    }
}

public enum MasterKeySource
{
    EnvironmentVariable,
    File,
    AutoGeneratedFile
}
